//#define LUA_COMPAT_5_1
//#define LUA_COMPAT_5_2

// Lua source code only, relative .
#include "../../../LuaSourceCodeDir/src/luaconf.h"
#include "../../../LuaSourceCodeDir/src/bit.c"
#include "../../../LuaSourceCodeDir/src/int64.c"
#include "../../../LuaSourceCodeDir/src/lapi.c"
#include "../../../LuaSourceCodeDir/src/lauxlib.c"
#include "../../../LuaSourceCodeDir/src/lbaselib.c"
#include "../../../LuaSourceCodeDir/src/lcode.c"
#include "../../../LuaSourceCodeDir/src/ldblib.c"
#include "../../../LuaSourceCodeDir/src/ldebug.c"
#include "../../../LuaSourceCodeDir/src/ldo.c"
#include "../../../LuaSourceCodeDir/src/ldump.c"
#include "../../../LuaSourceCodeDir/src/lfunc.c"
#include "../../../LuaSourceCodeDir/src/lgc.c"
#include "../../../LuaSourceCodeDir/src/linit.c"
#include "../../../LuaSourceCodeDir/src/liolib.c"
#include "../../../LuaSourceCodeDir/src/llex.c"
#include "../../../LuaSourceCodeDir/src/lmathlib.c"
#include "../../../LuaSourceCodeDir/src/lmem.c"
#include "../../../LuaSourceCodeDir/src/loadlib.c"
#include "../../../LuaSourceCodeDir/src/lobject.c"
#include "../../../LuaSourceCodeDir/src/lopcodes.c"
#include "../../../LuaSourceCodeDir/src/lparser.c"
#include "../../../LuaSourceCodeDir/src/lpeg.c"
#include "../../../LuaSourceCodeDir/src/lopcodes.c"
#include "../../../LuaSourceCodeDir/src/lparser.c"
#include "../../../LuaSourceCodeDir/src/lpeg.c"

#include "../../../LuaSourceCodeDir/src/lstate.c"
#include "../../../LuaSourceCodeDir/src/lstring.c"
#include "../../../LuaSourceCodeDir/src/lstrlib.c"

#include "../../../LuaSourceCodeDir/src/ltable.c"
#include "../../../LuaSourceCodeDir/src/ltablib.c"
#include "../../../LuaSourceCodeDir/src/ltm.c"
#include "../../../LuaSourceCodeDir/src/lundump.c"
#include "../../../LuaSourceCodeDir/src/lvm.c"
#include "../../../LuaSourceCodeDir/src/lzio.c"
#include "../../../LuaSourceCodeDir/src/pb.c"
#include "../../../LuaSourceCodeDir/src/print.c"
#include "../../../LuaSourceCodeDir/src/struct.c"

#include "../../../LuaSourceCodeDir/src/uint64.c"

#include "../../../LuaSourceCodeDir/src/tolua.c"